name: 자동 PR 라벨 추가

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pr_status_job:
    runs-on: ubuntu-latest

    steps:
      - name: 리포지토리 체크아웃
        uses: actions/checkout@v2

      - name: PR 상태 확인 및 라벨 추가하기
        run: |
          pr_numbers=$(gh pr list --json number --search "is:pr is:open -label:work-in-process" | jq -r '.[].number')
          label="work-in-process"
          for pr_number in $pr_numbers; do
            pr_status=$(gh pr view $pr_number --json state --jq .state)
            echo "PR 상태: $pr_status"
            if [ "$pr_status" = "OPEN" ]; then
              gh label view $label --repo ${{ github.repository }} 2>/dev/null || gh label create $label --repo ${{ github.repository }} --color FFA500 --description "This PR is a work in process"
              gh pr edit $pr_number --add-label $label
            fi
          done
        env:
          GH_TOKEN: ${{ secrets.CUSTOM_GH_TOKEN }}
