name: SonarQube 연동

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: 리포지토리 체크아웃
        uses: actions/checkout@v2

      - name: 캐시 로드
        uses: actions/cache@v2
        with:
          path: ~/.ghcup
          key: gh-extensions-${{ runner.os }}-${{ hashFiles('**/sonarqube.yaml') }}

      - name: 소나큐브 플러그인 설치
        run: gh extension install sonarqube

      - name: 소나큐브 토큰 생성
        run: gh sonarqube create-token --name "SonarQube Token" > sonarqube_token.txt

      - name: 소나큐브 통합 분석
        run: gh sonarqube analyze --linter --token "$(cat sonarqube_token.txt)"

      - name: 통합 결과 확인
        run: gh sonarqube check
