name: SonarQube 연동

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: 리포지토리 체크아웃
        uses: actions/checkout@v2

      - name: 캐시 로드
        uses: actions/cache@v2
        with:
          path: ~/.ghcup
          key: gh-extensions-${{ runner.os }}-${{ hashFiles('**/sonarqube.yaml') }}

      - name: 소나큐브 플러그인 설치
        run: gh extension install sonarqube/sonarqube
        env:
          GH_TOKEN: ${{ secrets.CUSTOM_GH_TOKEN }}

      - name: 소나큐브 토큰 생성
        run: gh secret set SONARQUBE_TOKEN -b"$(gh sonarqube create-token --name "SonarQube Token")"
        env:
          GH_TOKEN: ${{ secrets.CUSTOM_GH_TOKEN }}

      - name: 소나큐브 통합 분석
        run: gh sonarqube analyze --linter --token ${{ secrets.SONARQUBE_TOKEN }}
        env:
          GH_TOKEN: ${{ secrets.CUSTOM_GH_TOKEN }}

      - name: 통합 결과 확인
        run: gh sonarqube check
        env:
          GH_TOKEN: ${{ secrets.CUSTOM_GH_TOKEN }}
