name: PR 오래된 알림

#on:
#  schedule:
#    - cron: '0 0 * * *'  # 매일 자정마다 실행

on: [workflow_dispatch]
  

jobs:
  pr_stale_notification_job:
    runs-on: ubuntu-latest

    steps:
      - name: 리포지토리 체크아웃
        uses: actions/checkout@v2

      - name: 오래된_PR_가져오기
        id: get_stale_prs
        run: |
          gh pr list --state open --json number --jq ".[] | .number"
        # gh pr list --state open --json number --jq ".[] | select(.updated_at < (now - 30*24*60*60)) | .number"
        env:
          GH_TOKEN: ${{ secrets.CUSTOM_GH_TOKEN }}

      - name: Slack 알림 전송
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: github-workflows
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          GH_TOKEN: ${{ secrets.CUSTOM_GH_TOKEN }}
          SLACK_TITLE: 'Stale PR'
          SLACK_MESSAGE: '생성된지 오래된 PR이 있습니다: ${{ steps.get_stale_prs.outputs.stdout }}'
          SLACK_USERNAME: 'GITHUB'
